# Generated by Django 4.2.29 on 2026-04-03 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eveonline', '0017_alliance_and_corp_names_are_not_unique'),
        ('moonmaster', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moon',
            name='ore_composition',
            field=models.JSONField(default=dict, help_text='Dict mapping ore type_id (str) to fractional abundance (0–1).', verbose_name='Ore Composition'),
        ),
        migrations.AlterField(
            model_name='moon',
            name='rarity_class',
            field=models.CharField(blank=True, choices=[('ubiquitous', 'R4 — Ubiquitous'), ('common', 'R8 — Common'), ('uncommon', 'R16 — Uncommon'), ('rare', 'R32 — Rare'), ('exceptional', 'R64 — Exceptional')], max_length=20, verbose_name='Rarity Class'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='goo_bay_fill_pct',
            field=models.FloatField(blank=True, help_text='Percentage of the moon material bay that is currently filled.', null=True, verbose_name='Goo Bay Fill %'),
        ),
        migrations.AlterField(
            model_name='structureowner',
            name='character',
            field=models.ForeignKey(blank=True, help_text='Character whose token is used for ESI pulls.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='eveonline.evecharacter', verbose_name='ESI Character'),
        ),
        migrations.AlterField(
            model_name='taxconfig',
            name='alliance_tax',
            field=models.FloatField(default=0.0, help_text='Fraction of mined ore value paid as alliance tax (e.g. 0.05 = 5%).', verbose_name='Alliance Mining Tax'),
        ),
        migrations.AlterField(
            model_name='taxconfig',
            name='corp_tax',
            field=models.FloatField(default=0.0, help_text='Fraction of mined ore value paid as corp tax.', verbose_name='Corp Mining Tax'),
        ),
        migrations.AlterField(
            model_name='taxconfig',
            name='reprocess_tax',
            field=models.FloatField(default=0.0, help_text='Tax taken by structure on reprocessing (fraction of output value).', verbose_name='Structure Reprocessing Tax'),
        ),
    ]
