# Generated by Django 4.2.29 on 2026-04-05 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moonmaster', '0006_fix_ore_type_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oreprice',
            name='source',
            field=models.CharField(choices=[('esi', 'ESI Average Price'), ('fuzzwork', 'Fuzzwork Buy/Sell'), ('janice', 'Janice Jita Buy (top-5%)')], default='esi', max_length=20, verbose_name='Price Source'),
        ),
        migrations.AlterField(
            model_name='ownercharacter',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
